MedPoint/Controllers/DoctorsController.cs
using MedPoint.Data;
using MedPoint.Data.Services;
using MedPoint.Models;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;

namespace MedPoint.Controllers
{
    public class DoctorsController : Controller
    {

        private readonly IDoctorsService _service;
        public DoctorsController(IDoctorsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Specialization")]Doctor doctor)
        {
            if (!ModelState.IsValid)
            {
                return View(doctor);
                

            }
            await _service.AddAsync(doctor);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var doctorEdit = await _service.GetByIdAsync(id);
            if (doctorEdit == null)
            {
                return View("Nie znaleziono");
            }
            return View(doctorEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Doctor doctor)
        {
            if (!ModelState.IsValid)
            {
                return View(doctor);


            }
            await _service.UpdateAsync(id, doctor);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var doctorEdit = await _service.GetByIdAsync(id);
            if (doctorEdit == null) return View("Nie znaleziono");
            return View(doctorEdit);
        }
        [HttpPost, ActionName("Delete")] 
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var doctor = await _service.GetByIdAsync(id);
            if (doctor == null) return View("Nie znaleziono");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MedPoint/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedPoint</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedPoint.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-bg-white text-danger" asp-area="" asp-controller="Home" asp-action="Index">MedPoint</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Strona Główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Doctors" asp-action="Index">Nasi specjaliści</a>
                        </li>
                    </ul>
                </div>
                <partial name ="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>