MedPoint/Controllers/HomeController.cs
using MedPoint.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using MedPoint.Data;

namespace MedPoint.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDBContext _context;

        public HomeController(ILogger<HomeController> logger, AppDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var data = _context.Doctors.ToList();
            return View(data);
        }

        public IActionResult Privacy()
        {         
            return View();
        }
        public IActionResult Visit()
        {
            return View("~/Views/Visits/Index.aspx");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MedPoint/Controllers/VisitsController.cs
using MedPoint.Data.Services;
using MedPoint.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MedPoint.Controllers
{
    public class VisitsController : Controller
    {
        private readonly IVisitsService _service;
        public VisitsController(IVisitsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(IdentityAccount account)
        {
            var model = await _service.GetDoctorsListAsync();
            model.StartDate = DateTime.Today;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Created([Bind("PatientName,DoctorName,StartDate")] Visit visit)
        {
            var doctorList = await _service.GetDoctorsListAsync();
            if (!ModelState.IsValid)
            {
                return View("Index", doctorList);

            }
            await _service.AddAsync(visit);
            return View("Created");
        }
    }
}

MedPoint/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<Doctor>
@{
    ViewData["Title"] = "MedPoint";
}


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title text-center">
                                    @item.FullName
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ProfilePictureURL" alt="@item.FullName" style="width: 250px; height: 200px">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>Specjalizacja: </b>@item.Specialization</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer bg-light">
                            <p class="card-text">
                                    
                                @if (User.Identity.IsAuthenticated)
                                {
                                  <a class="btn btn-success text-white"asp-controller="Visits"> Umów Wizytę</a>
                                }
                                else
                                {
                                    <a href="/Identity/Account/Login"class="btn btn-success text-white">Umów Wizytę</a>
                                }
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>